### ISSUE TITLE
CLI Logic Issues

### ISSUE THREAD

**Issue by Delinquent-Pointer** [hbarton2/cscd350-f24-AndTheyWereRoomates#143]
<img width="782" alt="image" src="https://github.com/user-attachments/assets/c1fb0fa5-e5aa-4422-b4d5-9aac3f9903a7">
<img width="842" alt="image" src="https://github.com/user-attachments/assets/8099d9bc-1700-46c6-b6c9-cb3991ccd9af">

**Comment by SimonLXiong** [comment]
The reason why the program crashes is because the crash handler doesn't prevent executing the main code. It'll flag the input being incorrect and then continue with the program when it should terminate. 

Problem is on Line 157 in CLIView

As a side note, the display text should really say "Try ``list class`` or ``list classes``", load is for something else entirely and doesn't even require a class name.
